#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0) [-v]"
	echo "    Push changes in Git repository located at $TODO_DIR."
        echo "    to <repo path> <branch name>."
	echo "    If -v argument is provided, only a preview will be shown."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"
git push -u origin master 
